### ISSUE TITLE
The real test size of AIDS

### ISSUE THREAD

**Issue by squareRoot3** [jiyangbai/TaGSim#2]
According to the paper, the test set of AIDS should have 800*20=16000 graph pairs. However, I found that `dataset/AIDS/ged_matrix_test` only contains 7119 unique graph pairs. What is the real test set size of AIDS?

**Comment by jiyangbai** [comment]
For AIDS the real test set, we tested all 800*20 graph pairs and finally only found 9 graphs that can compose graph pairs with the 800 graphs (due to high computational cost). So there are (800-1)*9 =7119 graph pairs in the real test set for AIDS. Sorry that we missed such statement in the paper.

**Comment by squareRoot3** [comment]
Got it. Thank you for your quick response!

**Comment by squareRoot3** [comment]
Could you share me the synthetic test set of the full AIDS dataset or the code for generating synthetic GED pairs?

**Comment by jiyangbai** [comment]
Hello, I have uploaded the code for generating synthetic graph pairs into the ./src/ directory. Note that please place it into the ./src/ directory to execute. Besides, the **proportion of Graph Edit Operations** is determined, to some extend randomly, but not totally random. You can specify the target GED values in prior, and make sure to follow some rules: for example in our design, the number of edge insertion is greater than number of node insertion, to avoid the newly added nodes becoming isolated nodes. Also the order of node relabeling, node insertion, edge insertion, edge deletion, edge relabeling is determined (which can be found in the code file), so that it can avoid the gaps between target GED and ground truth GED as much as possible.

**Comment by squareRoot3** [comment]
sincerely thanks !!!
